[theme]
primaryColor = "#22c55e"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#334155"
font = "sans serif"

[server]
maxUploadSize = 15
enableCORS = false
enableXsrfProtection = true

[browser]
serverPort = 8501
gatherUsageStats = false
