FROM python:3.9-slim

WORKDIR /app

# Gereksinimleri kopyala ve yükle
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Uygulama dosyalarını kopyala
COPY . .

# Streamlit ayarlarını kopyala
COPY .streamlit /app/.streamlit

# Streamlit'i başlat
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
